import { PetAffinity, PetEvolution, PetLineage, PetMood, PetState, StyleScoreKey } from '../core/petState';
import { PixelFrame, SpritePack } from './spriteTypes';

const palette = {
  '.': 'transparent',
  k: '#0f172a',
  s: '#334155',
  d: '#1e293b',
  w: '#f8fafc',
  g: '#86efac',
  y: '#facc15',
  o: '#fb923c',
  a: '#f97316',
  c: '#22d3ee',
  t: '#14b8a6',
  r: '#f87171',
  q: '#ef4444',
  b: '#60a5fa',
  n: '#2563eb',
  m: '#c084fc',
  v: '#a78bfa',
  p: '#f472b6'
};

const styleOrder: StyleScoreKey[] = ['builder', 'cleaner', 'debugger', 'scholar', 'streak'];
const lineageOrder: PetLineage[] = ['buildling', 'refact', 'debugon', 'archivox'];

const eggPixels = [
  '....kkkk....',
  '...kyyyyk...',
  '..kyywwyyk..',
  '.kyygccgyyk.',
  '.kygcsscgyk.',
  'kyygskksgyyk',
  'kyygskksgyyk',
  '.kygcsscgyk.',
  '.kyygccgyyk.',
  '..kyywwyyk..',
  '...kyssyk...',
  '....kkkk....'
];

const hatchlingPixels: Record<PetLineage, string[]> = {
  buildling: [
    '....kk......',
    '...koook....',
    '..kooooook..',
    '.kooyyyyook.',
    '.kooyggyook.',
    '.koowwwwook.',
    '.kooooooook.',
    '..kossook...',
    '...kook.....',
    '...o..o.....',
    '..oo..oo....',
    '............'
  ],
  refact: [
    '....cc......',
    '...ckkc.....',
    '..ckwwkc....',
    '.ckcccckc...',
    '.cscscckc...',
    '..ckkkkc....',
    '...ckkc.....',
    '..cc..cc....',
    '.cc....cc...',
    '.c......c...',
    '..cc..cc....',
    '............'
  ],
  debugon: [
    '....rr......',
    '...rkkkr....',
    '..rkkkkkr...',
    '.rkrwwrkr...',
    '.rkkrrkkr...',
    '..rkkkkkr...',
    '...rkkkr....',
    '..rr..rr....',
    '.r......r...',
    '..r....r....',
    '...r..r.....',
    '............'
  ],
  archivox: [
    '....bb......',
    '...bwwb.....',
    '..bwwwwb....',
    '.bwkwwkwb...',
    '.bwwbbwwb...',
    '..bwwwwb....',
    '...bwwb.....',
    '..bb..bb....',
    '.b......b...',
    '..b....b....',
    '...bbbb.....',
    '............'
  ]
};

const toolkitPixels: Record<PetLineage, string[]> = {
  buildling: [
    '......kkkk......',
    '....kkooookk....',
    '...kooooooook...',
    '..kooyyyyyoook..',
    '..kooygggyoook..',
    '.koowwwwwwoook..',
    '.koooooooooook..',
    '..kosssssssok...',
    '..koosssssook...',
    '...kookkkkook...',
    '...oo......oo...',
    '..ooo......ooo..',
    '..oo........oo..',
    '................',
    '................',
    '................'
  ],
  refact: [
    '.....cc..cc.....',
    '....ckkcckkc....',
    '...ckwwccwwkc...',
    '..ckcccccccckc..',
    '..cscsccccscc...',
    '.ckcccccccckc...',
    '.ccckkkkkkccc...',
    '..cckcccckcc....',
    '...ckcccckc.....',
    '..cck....kcc....',
    '.cc........cc...',
    '.c..........c...',
    '..cc......cc....',
    '...cccccccc.....',
    '................',
    '................'
  ],
  debugon: [
    '....rr....rr....',
    '...rkkrrrrkkr...',
    '..rkkkrrrrkkkr..',
    '.rkkkrwwrkkkr...',
    '.rkkkrrrrkkkr...',
    '..rkkkrrkkkr....',
    '...rkkkkkkr.....',
    '..rrkrrrrkrr....',
    '.r..krrrrk..r...',
    'r...krrrrk...r..',
    '....rkrrkr......',
    '...rr....rr.....',
    '..rr......rr....',
    '................',
    '................',
    '................'
  ],
  archivox: [
    '.....bb..bb.....',
    '....bwwbbwwb....',
    '...bwwwwwwwwb...',
    '..bwwkwwwwkwwb..',
    '..bwwwbbbbwwwb..',
    '.bwwwwwwwwwwb...',
    '.bbwwwwwwwwbb...',
    '..bbwwbbwwbb....',
    '...bwwbbwwb.....',
    '..bbwwbbwwbb....',
    '.b....bbbb....b.',
    '......bbbb......',
    '.....bb..bb.....',
    '....bb....bb....',
    '................',
    '................'
  ]
};

const specialistPixels: Record<PetLineage, Record<PetAffinity, string[]>> = {
  buildling: {
    builder: [
      '........kkkkkkkk........',
      '......kkoooooooook......',
      '.....kooooooooooook.....',
      '....koooyyyyyyooook.....',
      '...koooyggggggyooook....',
      '..koooygwwwwwwgyooook...',
      '..koooogwkkkkwgoooook...',
      '.koooooowkkkkwoooooook..',
      '.koooooowwwwwwoooooook..',
      '.kooooossssssssooooook..',
      '..kooooskkkkkssoooook...',
      '..kooooskkkkkssoooook...',
      '...kooossssssssoooook...',
      '....koooooooooooook.....',
      '.....kooookkkkooook.....',
      '......ooo....ooo........',
      '....oooo......oooo......',
      '...oooook....koooo......',
      '..oooo..k....k..oooo....',
      '..oo....k....k....oo....',
      '........k....k..........',
      '.......yyy..yyy.........',
      '......yyyy..yyyy........',
      '........................'
    ],
    cleaner: [
      '........kkkkkkkk........',
      '......kkoooooooook......',
      '.....kooooooooooook.....',
      '....koooowwwwwwooook....',
      '...kooowccccccwoooook...',
      '..kooowcggggggcwoooook..',
      '..kooowcwkkkkwcwoooook..',
      '.kooooowkkkkkkwoooooook.',
      '.koooooowwwwwwoooooook..',
      '.koooossssssssssoooook..',
      '..koossccccccssoooook...',
      '..koossccccccssoooook...',
      '...koosssssssssooook....',
      '....kooooooooook........',
      '.....kooookkkkook.......',
      '......ooo....ooo........',
      '....ooooc....coooo......',
      '...oooocc....ccoooo.....',
      '..ooocccc....ccccoo.....',
      '....cccc......cccc......',
      '.....cc........cc.......',
      '........................',
      '........................',
      '........................'
    ],
    debugger: [
      '........kkkkkkkk........',
      '......kkoooooooook......',
      '.....kooooooooooook.....',
      '....kooorrrrrrooook.....',
      '...kooorggggggrkooook...',
      '..kooorwwwwwwwrkooook...',
      '..kooorwkkkkkwrkooook...',
      '.kooooorwkkkkwroooooook.',
      '.kooooorwwwwwrrooooook..',
      '.koooossssssssssoooook..',
      '..koossrrrrrrssoooook...',
      '..koossrkkkkrssoooook...',
      '...koosrrrrrrssooook....',
      '....koooooooooook.......',
      '.....koookkkkoook.......',
      '..rr..ooo....ooo..rr....',
      '.rkkroooo....oooorrr....',
      '.rkkkroo......oorrkr....',
      '..rrrr........rrrr......',
      '....r..........r........',
      '...rr..........rr.......',
      '........................',
      '........................',
      '........................'
    ],
    scholar: [
      '........kkkkkkkk........',
      '......kkoooooooook......',
      '.....kooooooooooook.....',
      '....kooobbbbbbooook.....',
      '...kooobwwwwwbkooook....',
      '..kooobwgggggwbkooook...',
      '..kooobwkkkkkwbkooook...',
      '.kooooobwkkkkwbooooook..',
      '.kooooobwwwwwbbooooook..',
      '.koooossssssssssoooook..',
      '..koossbbbbbbssoooook...',
      '..koossbwwwwbssoooook...',
      '...koosbbbbbbsooook.....',
      '....koooooooooook.......',
      '...bbkooookkkkoookbb....',
      '..bwwbooo....ooobwwb....',
      '.bwwwwb......bwwwwb.....',
      '.bbbbbb......bbbbbb.....',
      '...bb..........bb.......',
      '...bb..........bb.......',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    streak: [
      '........kkkkkkkk........',
      '......kkoooooooook......',
      '.....kooooooooooook.....',
      '....koooggggggooook.....',
      '...kooogygygygkooook....',
      '..kooogywwwwwygkooook...',
      '..kooogywkkkwygkooook...',
      '.kooooogwkkkwgoooooook..',
      '.kooooogwwwwwgoooooook..',
      '.koooossssssssssoooook..',
      '..koossggggggssoooook...',
      '..koossgkkkkgssoooook...',
      '...koosggggggsooook.....',
      '....koooooooooook.......',
      '.....koookkkkoook.......',
      '......ooo....ooo........',
      '..ggggooo....ooogggg....',
      '.gwwggoo......oogwwg....',
      '..gggg..........gggg....',
      '...g............g.......',
      '...gggggggggggggg.......',
      '........................',
      '........................',
      '........................'
    ]
  },
  refact: {
    builder: [
      '.........cc..cc.........',
      '........ckkcckkc........',
      '.......ckwwccwwkc.......',
      '......ckcccccccckc......',
      '.....ckcccooooccckc.....',
      '....ckcccooyyooccckc....',
      '...ckcccooyggyooccckc...',
      '..ckcccccwkkkkwccccckc..',
      '..ccsccccwkkkkwccccscc..',
      '..cccccccwwwwwwccccccc..',
      '...ccckkkkkkkkkkkccc....',
      '....cckcccccccckcc......',
      '.....ckcccccccckc.......',
      '....cckcccccccckcc......',
      '...cckccoooooocckcc.....',
      '..cckccoo....oocckcc....',
      '.cckcco........occkcc...',
      '.ckccco..yyyy..occckc...',
      '..cccc....yy....cccc....',
      '...cc....oooo....cc.....',
      '...c....oo..oo....c.....',
      '..cc....oo..oo....cc....',
      '........................',
      '........................'
    ],
    cleaner: [
      '.........cc..cc.........',
      '........ckkcckkc........',
      '.......ckwwccwwkc.......',
      '......ckcccccccckc......',
      '.....ckccccwwcccckc.....',
      '....ckcccwwccwwccckc....',
      '...ckcccwcggggcwccckc...',
      '..ckccccwkkkkkkwcccckc..',
      '..ccscccwkkkkkkwcccscc..',
      '..ccccccwwwwwwwwcccccc..',
      '...ccckkkkkkkkkkkccc....',
      '....cckcccccccckcc......',
      '.....ckcccccccckc.......',
      '....cckcccccccckcc......',
      '...cckcccccccccckcc.....',
      '..cckcccccwwccccckcc....',
      '.cckccccwwccwwcccckcc...',
      '.ckccccwccccccwcccckc...',
      '..cccccc..ww..cccccc....',
      '...cccc..cwwc..cccc.....',
      '....cc..cc..cc..cc......',
      '...cc..cc....cc..cc.....',
      '........................',
      '........................'
    ],
    debugger: [
      '.........cc..cc.........',
      '........ckkcckkc........',
      '.......ckwwccwwkc.......',
      '......ckcccccccckc......',
      '.....ckcccrrrrccckc.....',
      '....ckcccrwkkwrccckc....',
      '...ckcccrwrrrrwrccckc...',
      '..ckccccwkkkkkkwcccckc..',
      '..ccscccwkkkkkkwcccscc..',
      '..ccccccwwwwwwwwcccccc..',
      '...ccckkkkkkkkkkkccc....',
      '....cckcccccccckcc......',
      '.....ckcccccccckc.......',
      '....cckcccccccckcc......',
      '...cckccrrrrrrcckcc.....',
      '..cckccrr....rrcckcc....',
      '.cckccr........rcckcc...',
      '.ckcccr..rrrr..rccckc...',
      '..cccc....rr....cccc....',
      '...cc....rkkr....cc.....',
      '..rr....rk..kr....rr....',
      '.rkkr..rr....rr..rkkr...',
      '........................',
      '........................'
    ],
    scholar: [
      '.........cc..cc.........',
      '........ckkcckkc........',
      '.......ckwwccwwkc.......',
      '......ckcccccccckc......',
      '.....ckcccbbbbccckc.....',
      '....ckcccbwwwwbccckc....',
      '...ckcccbwccccwbccckc...',
      '..ckccccwkkkkkkwcccckc..',
      '..ccscccwkkkkkkwcccscc..',
      '..ccccccwwwwwwwwcccccc..',
      '...ccckkkkkkkkkkkccc....',
      '....cckcccccccckcc......',
      '.....ckcccccccckc.......',
      '....cckcccccccckcc......',
      '...cckccbbbbbbcckcc.....',
      '..cckccbwwwwwwbcckcc....',
      '.cckccbww....wwbcckcc...',
      '.ckcccbwb....bwccckc....',
      '..ccccbb......bbcccc....',
      '..bbbb..........bbbb....',
      '.bwwb............bwwb...',
      '.bbbb............bbbb...',
      '........................',
      '........................'
    ],
    streak: [
      '.........cc..cc.........',
      '........ckkcckkc........',
      '.......ckwwccwwkc.......',
      '......ckcccccccckc......',
      '.....ckcccggggccckc.....',
      '....ckcccgwwwwgccckc....',
      '...ckcccgccccccgccckc...',
      '..ckccccwkkkkkkwcccckc..',
      '..ccscccwkkkkkkwcccscc..',
      '..ccccccwwwwwwwwcccccc..',
      '...ccckkkkkkkkkkkccc....',
      '....cckcccccccckcc......',
      '.....ckcccccccckc.......',
      '....cckcccccccckcc......',
      '...cckccggggggcckcc.....',
      '..cckccgwgwgwgcckcc.....',
      '.cckccg........gcckcc...',
      '.ckcccg..gggg..gccckc...',
      '..cccc....gg....cccc....',
      '...cc...gggggg...cc.....',
      '..ggggggg....ggggggg....',
      '.gwwg..........gwwg.....',
      '........................',
      '........................'
    ]
  },
  debugon: {
    builder: [
      '......rr........rr......',
      '.....rkkrrrrrrrrkkr.....',
      '....rkkkrrrrrrrrkkkr....',
      '...rkkkrrroooorrrkkkr...',
      '..rkkkrrrooyyoorrrkkkr..',
      '.rkkkrrrooyggyooorrrkkk.',
      '.rkkkrrrwkkkkkkwrrrkkk..',
      '..rkkkrrwkkkkkkwrrkkk...',
      '...rkkkkwwwwwwwwkkkk....',
      '..rrkrrrrrrrrrrrrkrr....',
      '.r..krrrrrrrrrrrrk..r...',
      'r...krrrrrrrrrrrrk...r..',
      '....rkrrkkkkkkrrkr......',
      '...rrr..rrrrrr..rrr.....',
      '..rr....rrrrrr....rr....',
      '.rr....oooooo......rr...',
      '......ooyyyyoo..........',
      '......oo....oo..........',
      '.....oo......oo.........',
      '....oo........oo........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    cleaner: [
      '......rr........rr......',
      '.....rkkrrrrrrrrkkr.....',
      '....rkkkrrrrrrrrkkkr....',
      '...rkkkrrrccccrrrkkkr...',
      '..rkkkrrrcwwwwcrrrkkkr..',
      '.rkkkrrrcwggggwcrrrkkk..',
      '.rkkkrrrwkkkkkkwrrrkkk..',
      '..rkkkrrwkkkkkkwrrkkk...',
      '...rkkkkwwwwwwwwkkkk....',
      '..rrkrrrrrrrrrrrrkrr....',
      '.r..krrrrrrrrrrrrk..r...',
      'r...krrrrrrrrrrrrk...r..',
      '....rkrrkkkkkkrrkr......',
      '...rrr..rrrrrr..rrr.....',
      '..rr....rrrrrr....rr....',
      '.rr....cccccc......rr...',
      '......ccwwwwcc..........',
      '......cc....cc..........',
      '.....cc......cc.........',
      '....cc........cc........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    debugger: [
      '......rr........rr......',
      '.....rkkrrrrrrrrkkr.....',
      '....rkkkrrrrrrrrkkkr....',
      '...rkkkrrrrrrrrrrkkkr...',
      '..rkkkrrrpppppprrrkkkr..',
      '.rkkkrrrpwwwwwwprrrkkk..',
      '.rkkkrrrwkkkkkkwrrrkkk..',
      '..rkkkrrwkkkkkkwrrkkk...',
      '...rkkkkwwwwwwwwkkkk....',
      '..rrkrrrrrrrrrrrrkrr....',
      '.r..krrrrrrrrrrrrk..r...',
      'r...krrrrrrrrrrrrk...r..',
      '....rkrrkkkkkkrrkr......',
      '...rrr..rrrrrr..rrr.....',
      '..rr....rrrrrr....rr....',
      '.rr....rrrrrr......rr...',
      '......rrkkkkrr..........',
      '.....rrr.rr.rrr.........',
      '....rrr..rr..rrr........',
      '...rr....rr....rr.......',
      '..rr.....rr.....rr......',
      '........................',
      '........................',
      '........................'
    ],
    scholar: [
      '......rr........rr......',
      '.....rkkrrrrrrrrkkr.....',
      '....rkkkrrrrrrrrkkkr....',
      '...rkkkrrrbbbbrrrkkkr...',
      '..rkkkrrrbwwwwbrrrkkkr..',
      '.rkkkrrrbwggggwbrrrkkk..',
      '.rkkkrrrwkkkkkkwrrrkkk..',
      '..rkkkrrwkkkkkkwrrkkk...',
      '...rkkkkwwwwwwwwkkkk....',
      '..rrkrrrrrrrrrrrrkrr....',
      '.r..krrrrrrrrrrrrk..r...',
      'r...krrrrrrrrrrrrk...r..',
      '....rkrrkkkkkkrrkr......',
      '...rrr..rrrrrr..rrr.....',
      '..rr....rrrrrr....rr....',
      '.rr....bbbbbb......rr...',
      '......bbwwwwbb..........',
      '.....bb..bb..bb.........',
      '....bb...bb...bb........',
      '...bb....bb....bb.......',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    streak: [
      '......rr........rr......',
      '.....rkkrrrrrrrrkkr.....',
      '....rkkkrrrrrrrrkkkr....',
      '...rkkkrrrggggrrrkkkr...',
      '..rkkkrrrgwwwwgrrrkkkr..',
      '.rkkkrrrgwggggwgrrrkkk..',
      '.rkkkrrrwkkkkkkwrrrkkk..',
      '..rkkkrrwkkkkkkwrrkkk...',
      '...rkkkkwwwwwwwwkkkk....',
      '..rrkrrrrrrrrrrrrkrr....',
      '.r..krrrrrrrrrrrrk..r...',
      'r...krrrrrrrrrrrrk...r..',
      '....rkrrkkkkkkrrkr......',
      '...rrr..rrrrrr..rrr.....',
      '..rr....rrrrrr....rr....',
      '.rr....gggggg......rr...',
      '......ggwggwgg..........',
      '.....gg......gg.........',
      '....gggggggggggg........',
      '...gg..........gg.......',
      '........................',
      '........................',
      '........................',
      '........................'
    ]
  },
  archivox: {
    builder: [
      '........bb....bb........',
      '.......bwwbbbbwwb.......',
      '......bwwwwwwwwwwb......',
      '.....bwwkwwwwwwkwwb.....',
      '....bwwwbboooobbwwwb....',
      '...bwwwwbooyyoobwwwwb...',
      '..bwwwwwboggggobwwwwwb..',
      '..bbwwwbwkkkkwwbwwwbb...',
      '...bbwwwbkkkkbwwwbb.....',
      '....bwwwbbbbbbwwwb......',
      '...bbwwwwwwwwwwwwbb.....',
      '..b..bwwwwwwwwwwb..b....',
      '.....bwwbbbbbbwwb.......',
      '....bbwwb....bwwbb......',
      '...bwwbb......bbwwb.....',
      '..bwwwb..oooo..bwwwb....',
      '..bbbb...oyyo...bbbb....',
      '.........oooo...........',
      '........oo..oo..........',
      '.......oo....oo.........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    cleaner: [
      '........bb....bb........',
      '.......bwwbbbbwwb.......',
      '......bwwwwwwwwwwb......',
      '.....bwwkwwwwwwkwwb.....',
      '....bwwwbbccccbbwwwb....',
      '...bwwwwbcwwwwcbwwwwb...',
      '..bwwwwwbcggggcbwwwwwb..',
      '..bbwwwbwkkkkwwbwwwbb...',
      '...bbwwwbkkkkbwwwbb.....',
      '....bwwwbbbbbbwwwb......',
      '...bbwwwwwwwwwwwwbb.....',
      '..b..bwwwwwwwwwwb..b....',
      '.....bwwbbbbbbwwb.......',
      '....bbwwb....bwwbb......',
      '...bwwbb......bbwwb.....',
      '..bwwwb..cccc..bwwwb....',
      '..bbbb...cwwc...bbbb....',
      '.........cccc...........',
      '........cc..cc..........',
      '.......cc....cc.........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    debugger: [
      '........bb....bb........',
      '.......bwwbbbbwwb.......',
      '......bwwwwwwwwwwb......',
      '.....bwwkwwwwwwkwwb.....',
      '....bwwwbbrrrrbbwwwb....',
      '...bwwwwbrwwwwrbwwwwb...',
      '..bwwwwwbrggggrbwwwwwb..',
      '..bbwwwbwkkkkwwbwwwbb...',
      '...bbwwwbkkkkbwwwbb.....',
      '....bwwwbbbbbbwwwb......',
      '...bbwwwwwwwwwwwwbb.....',
      '..b..bwwwwwwwwwwb..b....',
      '.....bwwbbbbbbwwb.......',
      '....bbwwb....bwwbb......',
      '...bwwbb......bbwwb.....',
      '..bwwwb..rrrr..bwwwb....',
      '..bbbb...rkkr...bbbb....',
      '.........rrrr...........',
      '........rr..rr..........',
      '.......rr....rr.........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    scholar: [
      '........bb....bb........',
      '.......bwwbbbbwwb.......',
      '......bwwwwwwwwwwb......',
      '.....bwwkwwwwwwkwwb.....',
      '....bwwwbbmmmmbbwwwb....',
      '...bwwwwbmwwwwmbwwwwb...',
      '..bwwwwwbmggggmbwwwwwb..',
      '..bbwwwbwkkkkwwbwwwbb...',
      '...bbwwwbkkkkbwwwbb.....',
      '....bwwwbbbbbbwwwb......',
      '...bbwwwwwwwwwwwwbb.....',
      '..b..bwwwwwwwwwwb..b....',
      '.....bwwbbbbbbwwb.......',
      '....bbwwb....bwwbb......',
      '...bwwbb......bbwwb.....',
      '..bwwwb..mmmm..bwwwb....',
      '..bbbb...mwwm...bbbb....',
      '.........mmmm...........',
      '........mm..mm..........',
      '.......mm....mm.........',
      '........................',
      '........................',
      '........................',
      '........................'
    ],
    streak: [
      '........bb....bb........',
      '.......bwwbbbbwwb.......',
      '......bwwwwwwwwwwb......',
      '.....bwwkwwwwwwkwwb.....',
      '....bwwwbbggggbbwwwb....',
      '...bwwwwbgwwwwgbwwwwb...',
      '..bwwwwwbggggggbwwwwwb..',
      '..bbwwwbwkkkkwwbwwwbb...',
      '...bbwwwbkkkkbwwwbb.....',
      '....bwwwbbbbbbwwwb......',
      '...bbwwwwwwwwwwwwbb.....',
      '..b..bwwwwwwwwwwb..b....',
      '.....bwwbbbbbbwwb.......',
      '....bbwwb....bwwbb......',
      '...bwwbb......bbwwb.....',
      '..bwwwb..gggg..bwwwb....',
      '..bbbb...gwwg...bbbb....',
      '.........gggg...........',
      '........gg..gg..........',
      '.......gg....gg.........',
      '........................',
      '........................',
      '........................',
      '........................'
    ]
  }
};

const ultimatePixels: Record<PetLineage, string[]> = {
  buildling: [
    '...........mmmmmmmmmm...........',
    '..........moooooooooom..........',
    '.........moooooooooooom.........',
    '........mooooyyyyyyoooom........',
    '.......mooooygggggggyooom.......',
    '......mooooygwkkkkwwgyooom......',
    '.....mooooogwkkkkkkwgooooom.....',
    '....moooooogwwwwwwwwgoooooom....',
    '...mooooooossssssssssooooooom...',
    '..mooooooooskkkkkkkksoooooooom..',
    '..mooooooooskkkkkkkksoooooooom..',
    '..moooooooossssssssssoooooooom..',
    '...moooooooookkkkkooooooooom....',
    '....moooooooooyyoooooooooom.....',
    '.....mooooooooyyooooooooom......',
    '......moooooooyyoooooooom.......',
    '...ooooomoooooyyooooomoooooo....',
    '..ooooooomooooyyoooomooooooo....',
    '.ooo....oomoooyyooomoo....ooo...',
    '.oo......omoooyyooomo......oo...',
    '.........omoooyyooomo...........',
    '.........omoooyyooomo...........',
    '........ooooooyyoooooo..........',
    '.......oooooooyyooooooo.........',
    '......oooooo......oooooo........',
    '.....oooooo........oooooo.......',
    '....oooooo..........oooooo......',
    '...oooooo............oooooo.....',
    '................................',
    '................................',
    '................................',
    '................................'
  ],
  refact: [
    '.............mm..mm.............',
    '............mccmmccm............',
    '...........mccwccwccm...........',
    '..........mccccccccccm..........',
    '.........mccccwwwwccccm.........',
    '........mcccwwccccwwcccm........',
    '.......mcccwcggggggcwcccm.......',
    '......mccccwkkkkkkkkwccccm......',
    '.....mcccccwkkkkkkkkwcccccm.....',
    '....mccccccwwwwwwwwwwccccccm....',
    '.....mccckkkkkkkkkkkkkkcccm.....',
    '......mcckcccccccccccckccm......',
    '.......mckcccccccccccckcm.......',
    '......mcckcccccccccccckccm......',
    '.....mcckcccccccccccccckccm.....',
    '....mcckcccccccccccccccckccm....',
    '...mcckcccccwwwwwwcccccckccm....',
    '..mcckccccwwccccccwwccccckccm...',
    '.mcckcccwwccccccccccwwccckccm...',
    '.mccccccccc........cccccccccm...',
    '..mccccccc..........cccccccm....',
    '...mccccc............cccccm.....',
    '....mccc..............cccm......',
    '.....mc................cm.......',
    '....cc..................cc......',
    '...cc....................cc.....',
    '..cc......................cc....',
    '.cc........................cc...',
    '................................',
    '................................',
    '................................',
    '................................'
  ],
  debugon: [
    '.........mm..........mm.........',
    '........mrrmmmmmmmmmmrrm........',
    '.......mrrrmmmmmmmmmmrrrm.......',
    '......mrrrmmrrrrrrrrmmrrrm......',
    '.....mrrrmmrpppppppprmmrrrm.....',
    '....mrrrmmrpwwwwwwwwprmmrrrm....',
    '...mrrrmmrrwkkkkkkkkwrrmmrrrm...',
    '..mrrrmmmrrwkkkkkkkkwrrmmmrrrm..',
    '.mrrrrmmmmrwwwwwwwwwwrmmmmrrrrm.',
    '.mrrrmmrrrrrrrrrrrrrrrrmmrrrm...',
    '..mrrm..krrrrrrrrrrrrk..mrrm....',
    '...mm...krrrrrrrrrrrrk...mm.....',
    '........rkrrkkkkkkrrkr..........',
    '.......rrr..rrrrrr..rrr.........',
    '......rr....rrrrrr....rr........',
    '.....rr.....rrrrrr.....rr.......',
    '....rr......rrrrrr......rr......',
    '...rr......rrkkkkrr......rr.....',
    '..rr......rrr.rr.rrr......rr....',
    '.rr......rrr..rr..rrr......rr...',
    'rr......rr....rr....rr......rr..',
    '.......rr.....rr.....rr.........',
    '......rr......rr......rr........',
    '.....rr.......rr.......rr.......',
    '....rr........rr........rr......',
    '...rr.........rr.........rr.....',
    '..rr..........rr..........rr....',
    '.rr...........rr...........rr...',
    '................................',
    '................................',
    '................................',
    '................................'
  ],
  archivox: [
    '..........mm......mm............',
    '.........mbbmmmmmmbbm...........',
    '........mbwwbbbbbbwwbm..........',
    '.......mbwwwwwwwwwwwwbm.........',
    '......mbwwwkwwwwwwkwwwbm........',
    '.....mbwwwwbbmmmmbbwwwwbm.......',
    '....mbwwwwwbmwwwwmbwwwwwbm......',
    '...mbwwwwwwbmggggmbwwwwwwbm.....',
    '..mbbwwwwwbwkkkkwwbwwwwwbbm.....',
    '...mbbwwwwwbkkkkbwwwwwbbm.......',
    '....mbwwwwwbbbbbbwwwwwbm........',
    '...mbbwwwwwwwwwwwwwwwwbbm.......',
    '..mb..bwwwwwwwwwwwwwwb..bm......',
    '.....mbwwbbbbbbbbbbwwbm.........',
    '....mbbwwb........bwwbbm........',
    '...mbwwbb..........bbwwbm.......',
    '..mbwwwb....mmmm....bwwwbm......',
    '..mbbbb.....mwwm.....bbbbm......',
    '............mmmm................',
    '...........mm..mm...............',
    '..........mm....mm..............',
    '.........mm......mm.............',
    '........mm........mm............',
    '.......mm..........mm...........',
    '......bb............bb..........',
    '.....bwwb..........bwwb.........',
    '....bwwwwb........bwwwwb........',
    '...bbbbbbbb......bbbbbbbb.......',
    '................................',
    '................................',
    '................................',
    '................................'
  ]
};

function frame(width: number, height: number, pixels: string[]): PixelFrame {
  return {
    width,
    height,
    palette,
    pixels
  };
}

function pack(id: string, evolution: PetEvolution, mood: PetMood, pixels: string[]): SpritePack {
  return {
    id,
    evolution,
    mood,
    frames: [frame(pixels[0]?.length ?? 0, pixels.length, pixels)]
  };
}

function dominantStyle(state: PetState): StyleScoreKey {
  return styleOrder.reduce((best, key) => (
    state.styleScores[key] > state.styleScores[best] ? key : best
  ), styleOrder[0]);
}

function lineageFromStyle(style: StyleScoreKey): PetLineage {
  if (style === 'builder') {
    return 'buildling';
  }
  if (style === 'cleaner') {
    return 'refact';
  }
  if (style === 'debugger') {
    return 'debugon';
  }
  return 'archivox';
}

export const developerToolSpritePacks: SpritePack[] = [
  pack('egg-common-normal', 'egg', 'normal', eggPixels),
  ...lineageOrder.map((lineage) => pack(`${lineage}-hatchling-normal`, 'junior', 'normal', hatchlingPixels[lineage])),
  ...lineageOrder.map((lineage) => pack(`${lineage}-toolkit-normal`, 'mid', 'normal', toolkitPixels[lineage])),
  ...lineageOrder.flatMap((lineage) => styleOrder.map((affinity) => (
    pack(`${lineage}-specialist-${affinity}-normal`, 'senior', 'normal', specialistPixels[lineage][affinity])
  ))),
  ...lineageOrder.map((lineage) => pack(`${lineage}-ultimate-normal`, 'architect', 'normal', ultimatePixels[lineage]))
];

export function getDeveloperToolSpritePack(state: PetState, mood: PetMood): SpritePack {
  const style = dominantStyle(state);
  const lineage = state.lineage ?? lineageFromStyle(style);
  const affinity = state.affinity ?? style;
  let id: string;

  if (state.evolution === 'egg') {
    id = 'egg-common';
  } else if (state.evolution === 'junior') {
    id = `${lineage}-hatchling`;
  } else if (state.evolution === 'mid') {
    id = `${lineage}-toolkit`;
  } else if (state.evolution === 'senior') {
    id = `${lineage}-specialist-${affinity}`;
  } else {
    id = `${lineage}-ultimate`;
  }

  return developerToolSpritePacks.find((sprite) => sprite.id === `${id}-${mood}`)
    ?? developerToolSpritePacks.find((sprite) => sprite.id === `${id}-normal`)
    ?? developerToolSpritePacks[0];
}
